### ISSUE TITLE
Error: application token is invalid

### ISSUE THREAD

**Issue by LiveJDM** [paulmaunders/delivery-slot-bot#37]
Ive tried 2 new tokens, however still not working. Any ideas?

Error: application token is invalid
    at Pushover.errors (/Users/*****/Documents/delivery-slot-bot/node_modules/pushover-notifications/lib/pushover.js:146:13)
    at IncomingMessage.<anonymous> (/Users/*****/Documents/delivery-slot-bot/node_modules/pushover-notifications/lib/pushover.js:250:12)

**Comment by LiveJDM** [comment]
User error! Ignore
