### ISSUE TITLE
Cannot find module 'telegram-bot-api'

### ISSUE THREAD

**Issue by CharlesButcher** [paulmaunders/delivery-slot-bot#47]
What's up here?

````
~/delivery-slot-bot (master ✘)✭ ᐅ yarn start
yarn run v1.22.4
$ node ./src/index.js
internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module 'telegram-bot-api'
Require stack:
- /Users/charles/delivery-slot-bot/src/notifications/telegram.js
- /Users/charles/delivery-slot-bot/src/config.js
- /Users/charles/delivery-slot-bot/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/charles/delivery-slot-bot/src/notifications/telegram.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/charles/delivery-slot-bot/src/notifications/telegram.js',
    '/Users/charles/delivery-slot-bot/src/config.js',
    '/Users/charles/delivery-slot-bot/src/index.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by andytson** [comment]
run `yarn install` after each update you fetch from here

**Comment by CharlesButcher** [comment]
Oh, sorry, many thanks.

Asda will be cool!

**Comment by CharlesButcher** [comment]
Just looked at the Asda code. Thank you guys again for all your hard work.
