### ISSUE TITLE
Issue installing / Running

### ISSUE THREAD

**Issue by jpf198** [paulmaunders/delivery-slot-bot#65]
When running i get an error:

Any help or ideas woudl be appriciated.

Thanks
J

```
bitnami@debian:~/delivery-slot-bot$ yarn start
yarn run v1.22.4
$ node ./src/index.js
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'node-schedule'
Require stack:
- /home/bitnami/delivery-slot-bot/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/bitnami/delivery-slot-bot/src/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/bitnami/delivery-slot-bot/src/index.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jpf198** [comment]
had a look at issue [https://github.com/paulmaunders/delivery-slot-bot/issues/53](url) as you have gone through a lot of installation issues on that one.

`yarn install --check-files`

Has fixed the error for finding the modules, but now getting a chrome error.

`Error: Failed to launch chrome!
/home/bitnami/delivery-slot-bot/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
`

**Comment by jpf198** [comment]
installing puppeteer might help ;)

`npm i puppeteer`

**Comment by jpf198** [comment]
.... and yargs

`npm i yargs`

**Comment by jpf198** [comment]
... and moment-timezone

`npm i moment-timezone`

**Comment by jpf198** [comment]
then a missing chrome dependency....:

`sudo apt-get install libatk3.0-cil`

**Comment by jpf198** [comment]
think i have hit a deadend now... so some help would be appricated. Have ensured all the chrome depencies are there, and it is still comeing up with a libatk3.0 error even though it is there???

any advice would be appricated.

Thanks!

j

```
bitnami@debian:~/delivery-slot-bot$ yarn start
yarn run v1.22.4
$ node ./src/index.js
index.js

Runs one-off

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error: Failed to launch chrome!
/home/bitnami/delivery-slot-bot/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/bitnami/delivery-slot-bot/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/home/bitnami/delivery-slot-bot/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:208:15)
    at Interface.close (readline.js:401:8)
    at Socket.onend (readline.js:178:10)
    at Socket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jpf198** [comment]
and then do the chrome-sandbox fix you had in 53

AND WORKING!!!!

On Tesco.. Asda comes up with a "thinks you are a bot and is putting up a reCaptcha...

```
cd ./node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/
mv chrome_sandbox chrome-sandbox
sudo chown root chrome-sandbox
sudo chmod 4755 chrome-sandbox
```
