### ISSUE TITLE
Timeout exceeded for Morrisons

### ISSUE THREAD

**Issue by ryanc414** [paulmaunders/delivery-slot-bot#74]
Hi, first of all thanks for publishing this app! I'm trying to get a delivery slot for my nan so hopefully this can help.

I entered my Morrison's login details in the config.ini but I noticed that it always seems to time out when checking delivery slots for Morrisons. I can log in and browse for delivery slots just fine in my web browser but I am getting a timeout error every time the app runs. Any ideas?

```
app_1     | 1589121921238 - Morrisons - Sun, 10 May 2020 14:45:21 GMT
app_1     | Logging in with new user session
app_1     | unexpected error:
app_1     | TimeoutError: Navigation timeout of 30000 ms exceeded
app_1     |     at /app/node_modules/puppeteer/lib/LifecycleWatcher.js:101:25
app_1     |     at async FrameManager.waitForFrameNavigation (/app/node_modules/puppeteer/lib/FrameManager.js:133:23)
app_1     |     at async Frame.waitForNavigation (/app/node_modules/puppeteer/lib/FrameManager.js:383:16)
app_1     |     at async Page.waitForNavigation (/app/node_modules/puppeteer/lib/Page.js:642:16)
app_1     |     at async Promise.all (index 0)
app_1     |     at async clickAndWaitForNavigation (/app/src/puppeteer-utils.js:72:6)
app_1     |     at async MorrisonsStore.login (/app/src/stores/morrisons.js:66:5)
app_1     |     at async MorrisonsStore.start (/app/src/stores/morrisons.js:94:7)
app_1     |     at async MorrisonsStore.checkDeliveries (/app/src/stores/morrisons.js:109:5)
app_1     |     at async runStore (/app/src/index.js:33:44)
app_1     |     at async run (/app/src/index.js:57:5)
app_1     |   -- ASYNC --
app_1     |     at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:82:19)
app_1     |     at Page.waitForNavigation (/app/node_modules/puppeteer/lib/Page.js:642:53)
app_1     |     at Page.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:83:27)
app_1     |     at clickAndWaitForNavigation (/app/src/puppeteer-utils.js:72:30)
app_1     |     at MorrisonsStore.login (/app/src/stores/morrisons.js:66:11)
app_1     |     at runMicrotasks (<anonymous>)
app_1     |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
app_1     |     at async MorrisonsStore.start (/app/src/stores/morrisons.js:94:7)
app_1     |     at async MorrisonsStore.checkDeliveries (/app/src/stores/morrisons.js:109:5)
app_1     |     at async runStore (/app/src/index.js:33:44)
app_1     |     at async run (/app/src/index.js:57:5)
```

**Comment by guowentian** [comment]
Same issue here.
